spring.application.name=CommunistDate
spring.datasource.url=jdbc:postgresql://cbec45869p4jbu.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com:5432/dcba0196f3fnu4
spring.datasource.username=ucn2roppbcvf5n
spring.datasource.password=paf44f5ea7370f1a2ef451b247cc47684b88540a2a0b6f956d0f08d57b4f15229
spring.datasource.driver-class-name=org.postgresql.Driver
security.jwt.secret-key=cicciobombogoleador1983PippoInzago1984BillyBalloBelloBullo1091729172319
security.jwt.token-validity=3600000
security.jwt.token-issuer=CommunistDate

logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=DEBUG
logging.level.com.example.CommunistDate=DEBUG
logging.file.name=app.log
logging.level.org.springframework.web.socket=DEBUG